# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190613_0033'),
        ('profiles', '0002_auto_20190613_0042'),
    ]

    operations = [
    ]
