# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='advertise',
            new_name='advertises',
        ),
    ]
