# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190609_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='advertises',
            field=models.ManyToManyField(blank=True, to='advertise.Advertise'),
        ),
    ]
