# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('major', models.CharField(choices=[('P', 'Public'), ('CE', 'Computer Engineering'), ('EE', 'Electrical Engineering')], default='P', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('P', 'Pending'), ('PB', 'Published'), ('C', 'Closed')], default='P', max_length=10)),
                ('page_numbers', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('release_year', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
