# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertise/images', verbose_name='Advertise image')),
            ],
        ),
        migrations.AlterField(
            model_name='advertise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='major',
            field=models.CharField(choices=[('P', 'Public'), ('CE', 'Computer Engineering'), ('EE', 'Electrical Engineering')], default='P', max_length=10, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='page_numbers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page numbers'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='release_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('PB', 'Published'), ('C', 'Closed')], default='P', max_length=10, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='advertiseimage',
            name='advertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.Advertise'),
        ),
    ]
