# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20190327_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='County name')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Province name')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='advertise.Province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='county',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.County', verbose_name='County'),
        ),
    ]
