# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_auto_20190411_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.County', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.University', verbose_name='University'),
        ),
    ]
