# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 16:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0008_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
